repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check .
        language: system
        pass_filenames: false
        always_run: true

      - id: run-tests
        name: run tests (test_*.py)
        entry: python -m unittest discover -s tests -p 'test_*.py'
        language: system
        pass_filenames: false
        always_run: true
