site_name: rxxxt
site_url: https://leopf.github.io/rxxxt/
repo_url: https://github.com/leopf/rxxxt
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: lime
nav:
  - Home: index.md
  - app.md
  - asgi.md
  - elements.md
  - component.md
  - router.md
  - path-matching.md
  - state.md
  - api.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            heading_level: 3
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            merge_init_into_class: true
            show_if_no_docstring: true
            show_source: true
            summary: true
