name: deploy docs
on:
  push:
    branches:
      - master
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: |
            pyproject.toml

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]

      - name: Run Prepare Docs Script
        run: python extra/preparedocs.py

      - name: Build
        run: mkdocs build --strict

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MKDOCS_GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
