name: Release
on: workflow_dispatch
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build web assets
        run: pnpm install && pnpm build:prod

      - name: Build the package
        run: python -m build -s
        
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: py-sdist
          path: dist

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build-sdist]
    timeout-minutes: 20
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Download sdist artifact
        uses: actions/download-artifact@v4
        with:
          name: py-sdist
          path: dist

      - name: Extract version from pyproject.toml
        id: extract_version
        run: echo "version=$(grep -oP '(?<=version = ")[^"]+' pyproject.toml | head -1)" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          body: Release ${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  publish-to-pypi:
    name: publish python distribution to PyPI
    needs: [build-sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/streamtasks
    permissions:
      id-token: write
    steps:
    - name: Download sdist artifact
      uses: actions/download-artifact@v4
      with:
        name: py-sdist
        path: dist
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1